# Generated by Django 5.0.3 on 2024-05-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
