# Generated by Django 5.0.3 on 2024-05-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_commande_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
    ]
